TRAIN:
  LR_WARM_UP: False
  CLIP_GRAD: True
  END2END: False
  BATCH_SIZE: 4
  DO_VALIDATION: True
DATA:
  IMAGE_MIN_DIM: 800
  IMAGE_MAX_DIM: 1024
DEV:
  SWITCH: True
  BUFFER_SIZE: 2000
  LOSS_CHOICE: 'kl'
  LOSS_FAC: 200.
MODEL:
  INIT_FILE_CHOICE: 'coco_pretrain'
CTRL:
  QUICK_VERIFY: True
