TRAIN:
  LR_WARM_UP: False
  CLIP_GRAD: True
  END2END: False
  BATCH_SIZE: 16
  DO_VALIDATION: False  # hasn't set up the test phase of meta-loss
DATA:
  IMAGE_MIN_DIM: 800
  IMAGE_MAX_DIM: 1024
DEV:
  SWITCH: True
  BUFFER_SIZE: 2000
MODEL:
  INIT_FILE_CHOICE: 'coco_pretrain'
