TRAIN:
  LR_WARM_UP: True
  CLIP_GRAD: False
  END2END: True    # turn on set_trainable option
  BATCH_SIZE: 16
DATA:
  IMAGE_MIN_DIM: 704
  IMAGE_MAX_DIM: 1024
MODEL:
  INIT_FILE_CHOICE: 'coco_pretrain'
